[project]
name = "ccs521fa26hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Kevin Fisher", email = "kfish610@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
  "certifi>=2026.7.22",
  "jupyter>=1.1.1",
  "matplotlib>=3.11.2",
  "notebook>=7.6.3",
  "numpy>=2.5.3",
  "tensorboardx>=2.6.5",
  "torch>=2.14.0",
  "torchvision>=0.29.0",
  "tqdm>=4.70.1",
  "triton-xpu>=3.8.0 ; sys_platform == 'linux'",
]

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/xpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-xpu" }
torchvision = { index = "pytorch-xpu" }
triton-xpu = { index = "pytorch-xpu" }


[project.scripts]
ccs521fa26hw = "ccs521fa26hw:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
